
import type { Plant } from './types';

export const plantData: Plant[] = [
  {
    id: '1',
    name: 'Swiss Cheese Plant',
    species: 'Monstera Deliciosa',
    size: 'Large',
    condition: 'Excellent',
    price: 315.0,
    seller: {
      name: 'Alex Greenfield',
      avatar: 'https://picsum.photos/id/1005/100/100',
    },
    images: [
      'https://picsum.photos/seed/real-monstera/800/800',
      'https://picsum.photos/seed/monstera-leaf-close/800/800',
      'https://picsum.photos/seed/monstera-in-pot/800/800',
      'https://picsum.photos/seed/monstera-angle/800/800',
    ],
    description: 'A beautiful, healthy Monstera Deliciosa with stunning leaf fenestrations. A statement piece for any bright room. Comes in a 25cm stylish ceramic pot.',
    stock: 2,
  },
  {
    id: '2',
    name: 'Mother-in-Law\'s Tongue',
    species: 'Dracaena trifasciata',
    size: 'Medium',
    condition: 'Good',
    price: 165.0,
    seller: {
      name: 'Jane Evergreen',
      avatar: 'https://picsum.photos/id/1011/100/100',
    },
    images: [
      'https://picsum.photos/seed/real-snake-plant/800/800',
      'https://picsum.photos/seed/snake-plant-white-pot/800/800',
      'https://picsum.photos/seed/tall-snake-plant/800/800',
    ],
    description: 'A hardy and striking Snake Plant, known for its air-purifying qualities and low maintenance needs. An ideal choice for beginners. Has a few minor leaf scars.',
    stock: 5,
  },
  {
    id: '3',
    name: 'Weeping Fig',
    species: 'Ficus benjamina',
    size: 'Large',
    condition: 'Excellent',
    price: 450.0,
    seller: {
      name: 'Alex Greenfield',
      avatar: 'https://picsum.photos/id/1005/100/100',
    },
    images: [
      'https://picsum.photos/seed/real-ficus/800/800',
      'https://picsum.photos/seed/ficus-tree-indoor/800/800',
    ],
    description: 'An elegant Weeping Fig tree with a braided trunk and lush, dense foliage. Adds a touch of sophistication to your living space or office.',
    stock: 1,
  },
  {
    id: '4',
    name: 'Golden Pothos',
    species: 'Epipremnum aureum',
    size: 'Small',
    condition: 'Good',
    price: 45.0,
    seller: {
      name: 'Green Thumbs Nursery',
      avatar: 'https://picsum.photos/id/1025/100/100',
    },
    images: ['https://picsum.photos/seed/real-pothos/800/800'],
    description: 'A vibrant Golden Pothos with variegated leaves, trailing elegantly from its pot. Very easy to care for and adaptable to various light conditions.',
    stock: 15,
  },
  {
    id: '5',
    name: 'Zanzibar Gem',
    species: 'Zamioculcas zamiifolia',
    size: 'Medium',
    condition: 'Excellent',
    price: 185.0,
    seller: {
      name: 'Jane Evergreen',
      avatar: 'https://picsum.photos/id/1011/100/100',
    },
    images: ['https://picsum.photos/seed/real-zz-plant/800/800'],
    description: 'A glossy, dark green ZZ Plant. Famous for being extremely drought-tolerant and happy in low light, making it a perfect office or home companion.',
    stock: 4,
  },
  {
    id: '6',
    name: 'Variegated Spider Plant',
    species: 'Chlorophytum comosum \'Vittatum\'',
    size: 'Small',
    condition: 'Excellent',
    price: 90.0,
    seller: {
      name: 'Alex Greenfield',
      avatar: 'https://picsum.photos/id/1005/100/100',
    },
    images: ['https://picsum.photos/seed/real-spider-plant/800/800'],
    description: 'A classic Variegated Spider Plant producing numerous "spiderettes". A fantastic air purifier, perfect for hanging baskets.',
    stock: 8,
  },
  {
    id: '7',
    name: 'Peacock Plant',
    species: 'Calathea makoyana',
    size: 'Medium',
    condition: 'Fair',
    price: 130.0,
    seller: {
      name: 'Green Thumbs Nursery',
      avatar: 'https://picsum.photos/id/1025/100/100',
    },
    images: [
      'https://picsum.photos/seed/real-calathea/800/800',
      'https://picsum.photos/seed/calathea-leaves-detail/800/800',
    ],
    description: 'A stunning Calathea with intricate, feather-like patterns on its leaves. Requires higher humidity and has some crispy edges, hence the lower price.',
    stock: 1,
  },
    {
    id: '8',
    name: 'Giant White Bird of Paradise',
    species: 'Strelitzia nicolai',
    size: 'Large',
    condition: 'Good',
    price: 350.0,
    seller: {
      name: 'Jane Evergreen',
      avatar: 'https://picsum.photos/id/1011/100/100',
    },
    images: [
        'https://picsum.photos/seed/real-bird-of-paradise/800/800'
    ],
    description: 'A majestic Bird of Paradise plant that brings a tropical vibe indoors. Features large, banana-like leaves. One leaf has a slight tear but is otherwise healthy.',
    stock: 2,
    },
    {
    id: '9',
    name: 'Fiddle Leaf Fig',
    species: 'Ficus lyrata',
    size: 'Medium',
    condition: 'Excellent',
    price: 275.0,
    seller: {
      name: 'Salmon',
      avatar: 'https://picsum.photos/id/1012/100/100',
    },
    images: ['https://picsum.photos/seed/real-fiddle-leaf/800/800'],
    description: 'A trendy Fiddle Leaf Fig with large, violin-shaped leaves. A favorite among interior designers for its dramatic presence.',
    stock: 3,
  },
  {
    id: '10',
    name: 'String of Pearls',
    species: 'Senecio rowleyanus',
    size: 'Small',
    condition: 'Good',
    price: 65.0,
    seller: {
      name: 'Bibbin',
      avatar: 'https://picsum.photos/id/1013/100/100',
    },
    images: ['https://picsum.photos/seed/real-string-pearls/800/800'],
    description: 'A delicate and whimsical String of Pearls plant. Its bead-like leaves cascade beautifully from a hanging pot.',
    stock: 10,
  },
  {
    id: '11',
    name: 'Rubber Plant',
    species: 'Ficus elastica \'Tineke\'',
    size: 'Medium',
    condition: 'Excellent',
    price: 210.0,
    seller: {
      name: 'Amit',
      avatar: 'https://picsum.photos/id/1014/100/100',
    },
    images: ['https://picsum.photos/seed/real-rubber-plant/800/800'],
    description: 'A striking variegated Rubber Plant with shades of green, cream, and pink. A colorful and easy-to-care-for addition to any collection.',
    stock: 4,
  },
  {
    id: '12',
    name: 'Cast Iron Plant',
    species: 'Aspidistra elatior',
    size: 'Medium',
    condition: 'Excellent',
    price: 369.0,
    seller: {
      name: 'Alex Greenfield',
      avatar: 'https://picsum.photos/id/1005/100/100',
    },
    images: ['https://picsum.photos/seed/cast-iron-plant/800/800'],
    description: 'The Cast Iron Plant is virtually indestructible, thriving on neglect. Its lush, dark green leaves add a touch of elegance to any low-light corner.',
    stock: 7,
  },
  {
    id: '13',
    name: 'Beginner Set',
    species: 'Snake Plant & ZZ Plant',
    size: 'Small',
    condition: 'Excellent',
    price: 309.0,
    seller: {
      name: 'Into The Woods',
      avatar: 'https://picsum.photos/id/1025/100/100',
    },
    images: ['https://picsum.photos/seed/beginner-set/800/800'],
    description: 'The perfect starter pack for any new plant parent. This set includes two of the most resilient plants: the Snake Plant and the ZZ Plant. Both are known for their low-maintenance nature.',
    stock: 10,
  },
  {
    id: '14',
    name: 'Java Fern',
    species: 'Microsorum pteropus',
    size: 'Small',
    condition: 'Excellent',
    price: 55.0,
    seller: {
      name: 'Aquascapers UAE',
      avatar: 'https://picsum.photos/id/1015/100/100',
    },
    images: ['https://picsum.photos/seed/java-fern/800/800'],
    description: 'A popular and hardy aquarium plant that thrives in a variety of conditions. Its unique leaf shape adds texture and depth to any aquascape.',
    stock: 20,
  },
  {
    id: '15',
    name: 'Anubias Nana',
    species: 'Anubias barteri var. nana',
    size: 'Small',
    condition: 'Excellent',
    price: 65.0,
    seller: {
      name: 'Aquascapers UAE',
      avatar: 'https://picsum.photos/id/1015/100/100',
    },
    images: ['https://picsum.photos/seed/anubias-nana/800/800'],
    description: 'A short, bushy plant with broad, dark green leaves. Anubias Nana is a slow-grower and can be attached to rocks or driftwood.',
    stock: 15,
  },
  {
    id: '16',
    name: 'Amazon Sword',
    species: 'Echinodorus grisebachii',
    size: 'Medium',
    condition: 'Good',
    price: 80.0,
    seller: {
      name: 'Aquascapers UAE',
      avatar: 'https://picsum.photos/id/1015/100/100',
    },
    images: ['https://picsum.photos/seed/amazon-sword/800/800'],
    description: 'A classic and beautiful centerpiece for any aquarium. It has large, sword-shaped leaves that create a lush, vibrant background.',
    stock: 10,
  },
  {
    id: '17',
    name: 'Dwarf Hairgrass',
    species: 'Eleocharis parvula',
    size: 'Small',
    condition: 'Excellent',
    price: 45.0,
    seller: {
      name: 'Aquascapers UAE',
      avatar: 'https://picsum.photos/id/1015/100/100',
    },
    images: ['https://picsum.photos/seed/dwarf-hairgrass/800/800'],
    description: 'Perfect for creating a lush, green carpet effect on the bottom of your aquarium. This plant spreads quickly under the right conditions.',
    stock: 25,
  },
  {
    id: '18',
    name: 'Nerve Plant',
    species: 'Fittonia albivenis',
    size: 'Small',
    condition: 'Excellent',
    price: 35.0,
    seller: {
      name: 'Terrarium World',
      avatar: 'https://picsum.photos/id/1016/100/100',
    },
    images: ['https://picsum.photos/seed/nerve-plant/800/800'],
    description: 'A striking plant with brightly veined leaves, perfect for adding a pop of color to any terrarium. Loves high humidity.',
    stock: 30,
  },
  {
    id: '19',
    name: 'Friendship Plant',
    species: 'Pilea involucrata',
    size: 'Small',
    condition: 'Excellent',
    price: 40.0,
    seller: {
      name: 'Terrarium World',
      avatar: 'https://picsum.photos/id/1016/100/100',
    },
    images: ['https://picsum.photos/seed/friendship-plant/800/800'],
    description: 'Known for its quilted, textured leaves, the Friendship Plant is a bushy, trailing plant that thrives in the enclosed environment of a terrarium.',
    stock: 22,
  },
  {
    id: '20',
    name: 'Maidenhair Fern',
    species: 'Adiantum',
    size: 'Small',
    condition: 'Good',
    price: 50.0,
    seller: {
      name: 'Terrarium World',
      avatar: 'https://picsum.photos/id/1016/100/100',
    },
    images: ['https://picsum.photos/seed/maidenhair-fern/800/800'],
    description: 'A delicate fern with fine, feathery fronds on black stems. It requires consistent moisture, making it an ideal candidate for a closed terrarium.',
    stock: 18,
  },
  {
    id: '21',
    name: 'Baby Tears',
    species: 'Soleirolia soleirolii',
    size: 'Small',
    condition: 'Excellent',
    price: 40.0,
    seller: {
      name: 'Terrarium World',
      avatar: 'https://picsum.photos/id/1016/100/100',
    },
    images: ['https://picsum.photos/seed/baby-tears-plant/800/800'],
    description: 'A delicate, creeping plant with tiny round leaves that forms a dense mat. It loves the high humidity of a terrarium and creates a lush, green carpet.',
    stock: 25,
  },
  {
    id: '22',
    name: 'Abstract Stone Sculpture',
    species: 'Polished River Stone',
    size: 'Medium',
    condition: 'Excellent',
    price: 450.0,
    seller: {
      name: 'Artisan Creations',
      avatar: 'https://picsum.photos/seed/artisan-seller/100/100',
    },
    images: ['https://picsum.photos/seed/stone-sculpture/800/800'],
    description: 'A beautiful, hand-carved abstract sculpture made from polished river stone. Its organic shape brings a sense of calm and nature to any space.',
    stock: 3,
  },
  {
    id: '23',
    name: 'Bronze Leaf Sculpture',
    species: 'Cast Bronze',
    size: 'Small',
    condition: 'Excellent',
    price: 280.0,
    seller: {
      name: 'Artisan Creations',
      avatar: 'https://picsum.photos/seed/artisan-seller/100/100',
    },
    images: ['https://picsum.photos/seed/bronze-leaf/800/800'],
    description: 'An elegant cast bronze sculpture in the shape of a large tropical leaf. Perfect for adding a touch of metallic shine to your decor.',
    stock: 5,
  },
  {
    id: '24',
    name: 'Kinetic Wind Sculpture',
    species: 'Stainless Steel',
    size: 'Large',
    condition: 'Excellent',
    price: 850.0,
    seller: {
      name: 'Modern Art Co.',
      avatar: 'https://picsum.photos/seed/modern-art-seller/100/100',
    },
    images: ['https://picsum.photos/seed/wind-sculpture/800/800'],
    description: 'A mesmerizing kinetic wind sculpture made from durable stainless steel. The interlocking parts move gracefully with the wind, creating a dynamic focal point for your garden.',
    stock: 2,
  },
  {
    id: '25',
    name: 'Ceramic Bird Set',
    species: 'Glazed Earthenware',
    size: 'Small',
    condition: 'Excellent',
    price: 120.0,
    seller: {
      name: 'Pottery Corner',
      avatar: 'https://picsum.photos/seed/pottery-seller/100/100',
    },
    images: ['https://picsum.photos/seed/ceramic-birds/800/800'],
    description: 'A set of three charming, hand-painted ceramic birds. Each piece is unique, adding a whimsical touch to your shelves or plant displays.',
    stock: 10,
  },
  {
    id: '26',
    name: 'Teak Garden Bench',
    species: 'Tectona grandis',
    size: 'Large',
    condition: 'Excellent',
    price: 1200.0,
    seller: {
      name: 'Outdoor Living',
      avatar: 'https://picsum.photos/seed/outdoor-seller/100/100',
    },
    images: ['https://picsum.photos/seed/teak-bench/800/800'],
    description: 'A classic and durable garden bench made from sustainably sourced teak wood. Perfect for creating a peaceful seating area in your garden or patio.',
    stock: 5,
  },
  {
    id: '27',
    name: 'Macrame Plant Hanger',
    species: 'Cotton Rope',
    size: 'Medium',
    condition: 'Excellent',
    price: 75.0,
    seller: {
      name: 'Boho Designs',
      avatar: 'https://picsum.photos/seed/boho-seller/100/100',
    },
    images: ['https://picsum.photos/seed/macrame-hanger/800/800'],
    description: 'A beautifully handcrafted macrame plant hanger made from 100% cotton rope. Ideal for displaying your favorite trailing plants and saving space.',
    stock: 15,
  },
  {
    id: '28',
    name: 'Betta Fish',
    species: 'Betta splendens',
    size: 'Small',
    condition: 'Excellent',
    price: 95.0,
    seller: {
      name: 'Aquatic Wonders',
      avatar: 'https://picsum.photos/seed/aquatic-seller/100/100',
    },
    images: ['https://picsum.photos/seed/betta-fish/800/800'],
    description: 'A vibrant and beautiful male Betta fish, also known as a Siamese fighting fish. Known for their brilliant colors and flowing fins.',
    stock: 8,
  },
  {
    id: '29',
    name: 'Neon Tetra',
    species: 'Paracheirodon innesi',
    size: 'Small',
    condition: 'Excellent',
    price: 15.0,
    seller: {
      name: 'Aquatic Wonders',
      avatar: 'https://picsum.photos/seed/aquatic-seller/100/100',
    },
    images: ['https://picsum.photos/seed/neon-tetra/800/800'],
    description: 'A small, active, and brightly colored fish. Neon Tetras are best kept in schools of six or more and add a dazzling streak of color to any community tank.',
    stock: 50,
  },
  {
    id: '30',
    name: 'Botanical Watercolor Print',
    species: 'Giclée Print',
    size: 'Medium',
    condition: 'Excellent',
    price: 250.0,
    seller: {
      name: 'Artful Prints',
      avatar: 'https://picsum.photos/seed/print-seller/100/100',
    },
    images: ['https://picsum.photos/seed/watercolor-print/800/800'],
    description: 'A high-quality Giclée print of a watercolor painting featuring a collection of delicate ferns. Printed on archival paper for long-lasting color.',
    stock: 20,
  },
  {
    id: '31',
    name: 'Abstract Floral Oil Painting',
    species: 'Oil on Canvas',
    size: 'Large',
    condition: 'Excellent',
    price: 1800.0,
    seller: {
      name: 'Fine Art Collective',
      avatar: 'https://picsum.photos/seed/fine-art-seller/100/100',
    },
    images: ['https://picsum.photos/seed/oil-painting/800/800'],
    description: 'An original, one-of-a-kind abstract oil painting inspired by a blooming garden. Rich textures and vibrant colors make this a stunning statement piece.',
    stock: 1,
  },
  {
    id: '32',
    name: 'Acacia Wood Plant Stand',
    species: 'Acacia Wood',
    size: 'Medium',
    condition: 'Excellent',
    price: 220.0,
    seller: {
      name: 'Outdoor Living',
      avatar: 'https://picsum.photos/seed/outdoor-seller/100/100',
    },
    images: ['https://picsum.photos/seed/plant-stand/800/800'],
    description: 'A mid-century modern plant stand crafted from solid acacia wood. Its minimalist design elevates your favorite potted plants.',
    stock: 12,
  },
  {
    id: '33',
    name: 'Rattan Hanging Chair',
    species: 'Natural Rattan',
    size: 'Large',
    condition: 'Excellent',
    price: 1800.0,
    seller: {
      name: 'Boho Designs',
      avatar: 'https://picsum.photos/seed/boho-seller/100/100',
    },
    images: ['https://picsum.photos/seed/hanging-chair/800/800'],
    description: 'A stylish and comfortable hanging rattan chair. Create a cozy reading nook indoors or on a covered patio. Includes a plush cushion.',
    stock: 3,
  },
  {
    id: '34',
    name: 'Guppy Trio',
    species: 'Poecilia reticulata',
    size: 'Small',
    condition: 'Excellent',
    price: 45.0,
    seller: {
      name: 'Aquatic Wonders',
      avatar: 'https://picsum.photos/seed/aquatic-seller/100/100',
    },
    images: ['https://picsum.photos/seed/guppies/800/800'],
    description: 'A trio of colorful and lively guppies (one male, two females). These fish are easy to care for and are prolific breeders.',
    stock: 15,
  },
  {
    id: '35',
    name: 'Amano Shrimp',
    species: 'Caridina multidentata',
    size: 'Small',
    condition: 'Excellent',
    price: 25.0,
    seller: {
      name: 'Aquatic Wonders',
      avatar: 'https://picsum.photos/seed/aquatic-seller/100/100',
    },
    images: ['https://picsum.photos/seed/amano-shrimp/800/800'],
    description: 'A hardworking and peaceful algae-eating shrimp. Amano shrimp are a great addition to any community tank to help keep it clean.',
    stock: 40,
  },
  {
    id: '36',
    name: 'Monstera Leaf Linocut Print',
    species: 'Linocut Print',
    size: 'Small',
    condition: 'Excellent',
    price: 180.0,
    seller: {
      name: 'Artful Prints',
      avatar: 'https://picsum.photos/seed/print-seller/100/100',
    },
    images: ['https://picsum.photos/seed/linocut-print/800/800'],
    description: 'A hand-carved and hand-pressed linocut print of a Monstera Deliciosa leaf. Each print is unique and signed by the artist.',
    stock: 25,
  },
  {
    id: '37',
    name: 'Desert Landscape Acrylic Painting',
    species: 'Acrylic on Canvas',
    size: 'Medium',
    condition: 'Excellent',
    price: 950.0,
    seller: {
      name: 'Fine Art Collective',
      avatar: 'https://picsum.photos/seed/fine-art-seller/100/100',
    },
    images: ['https://picsum.photos/seed/desert-painting/800/800'],
    description: 'An original acrylic painting capturing the warm, serene beauty of a desert sunset. Features cacti and distant mountains in a minimalist style.',
    stock: 1,
  }
];
