export interface InqueProduct {
  id: string;
  title: string;
  price: number;
  weight: string;
  image: string;
  description: string;
  deliveryTime: string;
  category: 'Snacks' | 'Drinks' | 'Groceries' | 'Daily Essentials' | 'Frozen' | 'Bakery';
}

export const inqueProductData: InqueProduct[] = [
  // Snacks (25)
  {
    id: 'inque-1',
    title: 'Organic Almonds',
    price: 18.50,
    weight: '250g',
    image: 'https://picsum.photos/seed/almonds/400/400',
    description: 'Crunchy and delicious organic almonds, perfect for a healthy snack.',
    deliveryTime: '10-15 min',
    category: 'Snacks',
  },
  {
    id: 'inque-7',
    title: 'Potato Chips - Sea Salt',
    price: 8.00,
    weight: '150g',
    image: 'https://picsum.photos/seed/potato-chips/400/400',
    description: 'Classic kettle-cooked potato chips with a touch of sea salt.',
    deliveryTime: '10-15 min',
    category: 'Snacks',
  },
  { id: 'inque-s3', title: 'Cashews Roasted & Salted', price: 22.00, weight: '250g', image: 'https://picsum.photos/seed/cashews/400/400', description: 'Buttery roasted and salted cashews.', deliveryTime: '10-15 min', category: 'Snacks' },
  { id: 'inque-s4', title: 'Dark Chocolate Bar 70%', price: 15.00, weight: '100g', image: 'https://picsum.photos/seed/dark-chocolate/400/400', description: 'Rich and intense 70% cacao dark chocolate.', deliveryTime: '10-15 min', category: 'Snacks' },
  { id: 'inque-s5', title: 'Rice Crackers', price: 9.50, weight: '100g', image: 'https://picsum.photos/seed/rice-crackers/400/400', description: 'Light and crispy gluten-free rice crackers.', deliveryTime: '10-15 min', category: 'Snacks' },
  { id: 'inque-s6', title: 'Hummus Original', price: 12.00, weight: '200g', image: 'https://picsum.photos/seed/hummus/400/400', description: 'Creamy and classic chickpea hummus.', deliveryTime: '12-18 min', category: 'Snacks' },
  { id: 'inque-s7', title: 'Popcorn Sea Salt', price: 7.00, weight: '80g', image: 'https://picsum.photos/seed/popcorn/400/400', description: 'Ready-to-eat popcorn lightly salted.', deliveryTime: '10-15 min', category: 'Snacks' },
  { id: 'inque-s8', title: 'Dried Mango Slices', price: 19.00, weight: '150g', image: 'https://picsum.photos/seed/dried-mango/400/400', description: 'Sweet and chewy dried mango slices.', deliveryTime: '10-15 min', category: 'Snacks' },
  { id: 'inque-s9', title: 'Olives Green Pitted', price: 14.00, weight: '300g', image: 'https://picsum.photos/seed/green-olives/400/400', description: 'Pitted green olives in brine.', deliveryTime: '12-18 min', category: 'Snacks' },
  { id: 'inque-s10', title: 'Pretzels', price: 6.50, weight: '200g', image: 'https://picsum.photos/seed/pretzels/400/400', description: 'Classic salted pretzels, perfect for dipping.', deliveryTime: '10-15 min', category: 'Snacks' },
  { id: 'inque-s11', title: 'Pistachios', price: 25.00, weight: '200g', image: 'https://picsum.photos/seed/pistachios/400/400', description: 'Roasted and salted pistachios in the shell.', deliveryTime: '10-15 min', category: 'Snacks' },
  { id: 'inque-s12', title: 'Wasabi Peas', price: 10.00, weight: '100g', image: 'https://picsum.photos/seed/wasabi-peas/400/400', description: 'Spicy and crunchy wasabi-coated green peas.', deliveryTime: '10-15 min', category: 'Snacks' },
  { id: 'inque-s13', title: 'Corn Tortilla Chips', price: 11.00, weight: '250g', image: 'https://picsum.photos/seed/tortilla-chips/400/400', description: 'Crispy corn chips, perfect for salsa.', deliveryTime: '10-15 min', category: 'Snacks' },
  { id: 'inque-s14', title: 'Trail Mix', price: 17.00, weight: '200g', image: 'https://picsum.photos/seed/trail-mix/400/400', description: 'A mix of nuts, seeds, and dried fruit for energy.', deliveryTime: '10-15 min', category: 'Snacks' },
  { id: 'inque-s15', title: 'Beef Jerky', price: 28.00, weight: '70g', image: 'https://picsum.photos/seed/beef-jerky/400/400', description: 'High-protein smoked beef jerky.', deliveryTime: '10-15 min', category: 'Snacks' },
  { id: 'inque-s16', title: 'Chocolate Chip Cookies', price: 14.00, weight: '4 pack', image: 'https://picsum.photos/seed/choc-chip-cookies/400/400', description: 'Classic soft-baked chocolate chip cookies.', deliveryTime: '12-18 min', category: 'Snacks' },
  { id: 'inque-s17', title: 'Gummy Bears', price: 9.00, weight: '150g', image: 'https://picsum.photos/seed/gummy-bears/400/400', description: 'Fruity and chewy gummy bear candies.', deliveryTime: '10-15 min', category: 'Snacks' },
  { id: 'inque-s18', title: 'Seaweed Snacks', price: 12.50, weight: '10g', image: 'https://picsum.photos/seed/seaweed-snacks/400/400', description: 'Crispy roasted seaweed snacks with sea salt.', deliveryTime: '10-15 min', category: 'Snacks' },
  { id: 'inque-s19', title: 'Protein Bar', price: 13.00, weight: '60g', image: 'https://picsum.photos/seed/protein-bar/400/400', description: 'Chocolate brownie flavored protein bar.', deliveryTime: '10-15 min', category: 'Snacks' },
  { id: 'inque-s20', title: 'Mini Cheese Crackers', price: 8.50, weight: '150g', image: 'https://picsum.photos/seed/cheese-crackers/400/400', description: 'Bite-sized crackers made with real cheese.', deliveryTime: '10-15 min', category: 'Snacks' },
  { id: 'inque-s21', title: 'Apple Slices', price: 10.00, weight: '1 pack', image: 'https://picsum.photos/seed/apple-slices/400/400', description: 'Fresh, crisp apple slices ready to eat.', deliveryTime: '10-15 min', category: 'Snacks' },
  { id: 'inque-s22', title: 'Yogurt Dip', price: 11.00, weight: '200g', image: 'https://picsum.photos/seed/yogurt-dip/400/400', description: 'Cool cucumber and mint yogurt dip.', deliveryTime: '12-18 min', category: 'Snacks' },
  { id: 'inque-s23', title: 'Peanut Butter Filled Pretzels', price: 16.00, weight: '200g', image: 'https://picsum.photos/seed/peanut-pretzels/400/400', description: 'Crunchy pretzel nuggets filled with creamy peanut butter.', deliveryTime: '10-15 min', category: 'Snacks' },
  { id: 'inque-s24', title: 'Fruit Leather Strips', price: 10.50, weight: '5 pack', image: 'https://picsum.photos/seed/fruit-leather/400/400', description: 'Assorted natural fruit leather strips.', deliveryTime: '10-15 min', category: 'Snacks' },
  { id: 'inque-s25', title: 'Spicy Mixed Nuts', price: 20.00, weight: '200g', image: 'https://picsum.photos/seed/spicy-nuts/400/400', description: 'A fiery mix of almonds, cashews, and peanuts.', deliveryTime: '10-15 min', category: 'Snacks' },

  // Drinks (25)
  {
    id: 'inque-2',
    title: 'Sparkling Water',
    price: 4.00,
    weight: '500ml',
    image: 'https://picsum.photos/seed/water-bottle/400/400',
    description: 'Crisp and refreshing sparkling mineral water.',
    deliveryTime: '10-15 min',
    category: 'Drinks',
  },
  {
    id: 'inque-8',
    title: 'Cold Brew Coffee',
    price: 16.00,
    weight: '250ml',
    image: 'https://picsum.photos/seed/cold-brew/400/400',
    description: 'Smooth and strong cold brew coffee, ready to drink.',
    deliveryTime: '10-15 min',
    category: 'Drinks',
  },
  { id: 'inque-d3', title: 'Fresh Orange Juice', price: 14.00, weight: '500ml', image: 'https://picsum.photos/seed/orange-juice/400/400', description: '100% freshly squeezed orange juice.', deliveryTime: '12-18 min', category: 'Drinks' },
  { id: 'inque-d4', title: 'Green Tea', price: 12.00, weight: '330ml', image: 'https://picsum.photos/seed/green-tea/400/400', description: 'Iced green tea with a hint of lemon.', deliveryTime: '10-15 min', category: 'Drinks' },
  { id: 'inque-d5', title: 'Cola Classic', price: 5.00, weight: '330ml', image: 'https://picsum.photos/seed/cola-can/400/400', description: 'The classic cola taste you love.', deliveryTime: '10-15 min', category: 'Drinks' },
  { id: 'inque-d6', title: 'Kombucha Ginger', price: 18.00, weight: '330ml', image: 'https://picsum.photos/seed/kombucha/400/400', description: 'Fermented tea with a spicy ginger kick.', deliveryTime: '10-15 min', category: 'Drinks' },
  { id: 'inque-d7', title: 'Almond Milk', price: 15.00, weight: '1L', image: 'https://picsum.photos/seed/almond-milk/400/400', description: 'Unsweetened almond milk, perfect for cereals.', deliveryTime: '12-18 min', category: 'Drinks' },
  { id: 'inque-d8', title: 'Coconut Water', price: 10.00, weight: '330ml', image: 'https://picsum.photos/seed/coconut-water/400/400', description: 'Natural and hydrating coconut water.', deliveryTime: '10-15 min', category: 'Drinks' },
  { id: 'inque-d9', title: 'Diet Cola', price: 5.00, weight: '330ml', image: 'https://picsum.photos/seed/diet-cola/400/400', description: 'Zero calorie cola for a guilt-free treat.', deliveryTime: '10-15 min', category: 'Drinks' },
  { id: 'inque-d10', title: 'Iced Latte', price: 17.00, weight: '250ml', image: 'https://picsum.photos/seed/iced-latte/400/400', description: 'A chilled and creamy iced latte.', deliveryTime: '10-15 min', category: 'Drinks' },
  { id: 'inque-d11', title: 'Still Mineral Water', price: 3.00, weight: '500ml', image: 'https://picsum.photos/seed/still-water/400/400', description: 'Pure and simple still mineral water.', deliveryTime: '10-15 min', category: 'Drinks' },
  { id: 'inque-d12', title: 'Lemonade', price: 9.00, weight: '500ml', image: 'https://picsum.photos/seed/lemonade/400/400', description: 'Classic sweet and tangy lemonade.', deliveryTime: '10-15 min', category: 'Drinks' },
  { id: 'inque-d13', title: 'Apple Juice', price: 13.00, weight: '500ml', image: 'https://picsum.photos/seed/apple-juice/400/400', description: 'Crisp and sweet 100% apple juice.', deliveryTime: '12-18 min', category: 'Drinks' },
  { id: 'inque-d14', title: 'Energy Drink', price: 11.00, weight: '250ml', image: 'https://picsum.photos/seed/energy-drink/400/400', description: 'Get a boost of energy when you need it most.', deliveryTime: '10-15 min', category: 'Drinks' },
  { id: 'inque-d15', title: 'Chocolate Milk', price: 8.00, weight: '300ml', image: 'https://picsum.photos/seed/choco-milk/400/400', description: 'Rich and creamy chocolate flavored milk.', deliveryTime: '10-15 min', category: 'Drinks' },
  { id: 'inque-d16', title: 'Tonic Water', price: 6.00, weight: '200ml', image: 'https://picsum.photos/seed/tonic-water/400/400', description: 'Perfect mixer for your favorite spirits.', deliveryTime: '10-15 min', category: 'Drinks' },
  { id: 'inque-d17', title: 'Ginger Ale', price: 6.00, weight: '330ml', image: 'https://picsum.photos/seed/ginger-ale/400/400', description: 'Bubbly and spicy ginger ale.', deliveryTime: '10-15 min', category: 'Drinks' },
  { id: 'inque-d18', title: 'Mango Lassi', price: 15.00, weight: '300ml', image: 'https://picsum.photos/seed/mango-lassi/400/400', description: 'A refreshing yogurt-based mango smoothie.', deliveryTime: '12-18 min', category: 'Drinks' },
  { id: 'inque-d19', title: 'Cranberry Juice', price: 14.00, weight: '1L', image: 'https://picsum.photos/seed/cranberry-juice/400/400', description: 'Tart and refreshing cranberry juice cocktail.', deliveryTime: '12-18 min', category: 'Drinks' },
  { id: 'inque-d20', title: 'Hot Chocolate Mix', price: 20.00, weight: '250g', image: 'https://picsum.photos/seed/hot-chocolate/400/400', description: 'Just add hot milk for a cozy treat.', deliveryTime: '10-15 min', category: 'Drinks' },
  { id: 'inque-d21', title: 'Soy Milk', price: 14.00, weight: '1L', image: 'https://picsum.photos/seed/soy-milk/400/400', description: 'A great dairy-free alternative.', deliveryTime: '12-18 min', category: 'Drinks' },
  { id: 'inque-d22', title: 'Grapefruit Soda', price: 7.00, weight: '330ml', image: 'https://picsum.photos/seed/grapefruit-soda/400/400', description: 'Tangy and sweet sparkling grapefruit drink.', deliveryTime: '10-15 min', category: 'Drinks' },
  { id: 'inque-d23', title: 'Probiotic Yogurt Drink', price: 9.00, weight: '100ml', image: 'https://picsum.photos/seed/probiotic-drink/400/400', description: 'A small drink packed with healthy probiotics.', deliveryTime: '10-15 min', category: 'Drinks' },
  { id: 'inque-d24', title: 'Iced Tea Peach', price: 12.00, weight: '500ml', image: 'https://picsum.photos/seed/peach-tea/400/400', description: 'Sweetened iced tea with a delicious peach flavor.', deliveryTime: '10-15 min', category: 'Drinks' },
  { id: 'inque-d25', title: 'Kefir', price: 16.00, weight: '500ml', image: 'https://picsum.photos/seed/kefir/400/400', description: 'A fermented milk drink with a tart flavor.', deliveryTime: '12-18 min', category: 'Drinks' },

  // Groceries (25)
  {
    id: 'inque-3',
    title: 'Fresh Strawberries',
    price: 22.00,
    weight: '1 pack',
    image: 'https://picsum.photos/seed/strawberries/400/400',
    description: 'Juicy, sweet, and locally sourced strawberries.',
    deliveryTime: '12-18 min',
    category: 'Groceries',
  },
  {
    id: 'inque-9',
    title: 'Organic Avocado',
    price: 9.00,
    weight: '1 piece',
    image: 'https://picsum.photos/seed/avocado/400/400',
    description: 'Creamy and ripe organic Hass avocado.',
    deliveryTime: '10-15 min',
    category: 'Groceries',
  },
  { id: 'inque-g3', title: 'Free-Range Eggs', price: 18.00, weight: '1 dozen', image: 'https://picsum.photos/seed/eggs/400/400', description: 'A dozen fresh free-range eggs.', deliveryTime: '12-18 min', category: 'Groceries' },
  { id: 'inque-g4', title: 'Organic Tomatoes', price: 12.00, weight: '500g', image: 'https://picsum.photos/seed/tomatoes/400/400', description: 'Ripe and juicy organic tomatoes on the vine.', deliveryTime: '12-18 min', category: 'Groceries' },
  { id: 'inque-g5', title: 'Cheddar Cheese Block', price: 25.00, weight: '250g', image: 'https://picsum.photos/seed/cheddar-cheese/400/400', description: 'A block of mature cheddar cheese.', deliveryTime: '12-18 min', category: 'Groceries' },
  { id: 'inque-g6', title: 'Baby Spinach', price: 10.00, weight: '150g', image: 'https://picsum.photos/seed/baby-spinach/400/400', description: 'Washed and ready-to-eat baby spinach.', deliveryTime: '12-18 min', category: 'Groceries' },
  { id: 'inque-g7', title: 'Greek Yogurt', price: 15.00, weight: '500g', image: 'https://picsum.photos/seed/greek-yogurt/400/400', description: 'Thick and creamy plain Greek yogurt.', deliveryTime: '12-18 min', category: 'Groceries' },
  { id: 'inque-g8', title: 'Chicken Breast Fillets', price: 30.00, weight: '500g', image: 'https://picsum.photos/seed/chicken-breast/400/400', description: 'Skinless and boneless chicken breast fillets.', deliveryTime: '15-20 min', category: 'Groceries' },
  { id: 'inque-g9', title: 'Bananas', price: 7.00, weight: '1 bunch', image: 'https://picsum.photos/seed/bananas/400/400', description: 'A bunch of fresh, ripe bananas.', deliveryTime: '12-18 min', category: 'Groceries' },
  { id: 'inque-g10', title: 'Cucumber', price: 4.00, weight: '1 piece', image: 'https://picsum.photos/seed/cucumber/400/400', description: 'A crisp and refreshing cucumber.', deliveryTime: '12-18 min', category: 'Groceries' },
  { id: 'inque-g11', title: 'Full Cream Milk', price: 8.00, weight: '1L', image: 'https://picsum.photos/seed/full-cream-milk/400/400', description: 'Fresh full cream dairy milk.', deliveryTime: '12-18 min', category: 'Groceries' },
  { id: 'inque-g12', title: 'Lemons', price: 5.00, weight: '2 pack', image: 'https://picsum.photos/seed/lemons/400/400', description: 'Two fresh and zesty lemons.', deliveryTime: '12-18 min', category: 'Groceries' },
  { id: 'inque-g13', title: 'Olive Oil', price: 35.00, weight: '500ml', image: 'https://picsum.photos/seed/olive-oil/400/400', description: 'Extra virgin olive oil for cooking and dressing.', deliveryTime: '12-18 min', category: 'Groceries' },
  { id: 'inque-g14', title: 'Onion', price: 3.00, weight: '500g', image: 'https://picsum.photos/seed/onions/400/400', description: 'A bag of brown onions.', deliveryTime: '12-18 min', category: 'Groceries' },
  { id: 'inque-g15', title: 'Garlic', price: 4.50, weight: '1 bulb', image: 'https://picsum.photos/seed/garlic/400/400', description: 'A whole bulb of fresh garlic.', deliveryTime: '12-18 min', category: 'Groceries' },
  { id: 'inque-g16', title: 'Pasta Spaghetti', price: 9.00, weight: '500g', image: 'https://picsum.photos/seed/spaghetti/400/400', description: 'Classic Italian spaghetti pasta.', deliveryTime: '12-18 min', category: 'Groceries' },
  { id: 'inque-g17', title: 'Pasta Sauce Tomato', price: 12.00, weight: '500g', image: 'https://picsum.photos/seed/pasta-sauce/400/400', description: 'Tomato and basil pasta sauce.', deliveryTime: '12-18 min', category: 'Groceries' },
  { id: 'inque-g18', title: 'Salted Butter', price: 16.00, weight: '250g', image: 'https://picsum.photos/seed/butter/400/400', description: 'Creamy salted butter for all your needs.', deliveryTime: '12-18 min', category: 'Groceries' },
  { id: 'inque-g19', title: 'Carrots', price: 6.00, weight: '500g', image: 'https://picsum.photos/seed/carrots/400/400', description: 'A bag of fresh, sweet carrots.', deliveryTime: '12-18 min', category: 'Groceries' },
  { id: 'inque-g20', title: 'Lettuce Iceberg', price: 7.00, weight: '1 head', image: 'https://picsum.photos/seed/lettuce/400/400', description: 'A crisp head of iceberg lettuce.', deliveryTime: '12-18 min', category: 'Groceries' },
  { id: 'inque-g21', title: 'Basmati Rice', price: 25.00, weight: '1kg', image: 'https://picsum.photos/seed/basmati-rice/400/400', description: 'Long-grain aromatic basmati rice.', deliveryTime: '12-18 min', category: 'Groceries' },
  { id: 'inque-g22', title: 'Blueberries', price: 18.00, weight: '125g', image: 'https://picsum.photos/seed/blueberries/400/400', description: 'A punnet of fresh, plump blueberries.', deliveryTime: '12-18 min', category: 'Groceries' },
  { id: 'inque-g23', title: 'Salmon Fillet', price: 45.00, weight: '200g', image: 'https://picsum.photos/seed/salmon-fillet/400/400', description: 'A fresh, high-quality salmon fillet.', deliveryTime: '15-20 min', category: 'Groceries' },
  { id: 'inque-g24', title: 'Mushrooms', price: 9.00, weight: '250g', image: 'https://picsum.photos/seed/mushrooms/400/400', description: 'A punnet of fresh white mushrooms.', deliveryTime: '12-18 min', category: 'Groceries' },
  { id: 'inque-g25', title: 'Bell Pepper', price: 5.00, weight: '1 piece', image: 'https://picsum.photos/seed/bell-pepper/400/400', description: 'A crisp, red bell pepper.', deliveryTime: '12-18 min', category: 'Groceries' },
  
  // Daily Essentials (25)
  {
    id: 'inque-4',
    title: 'All-Purpose Cleaner',
    price: 15.75,
    weight: '750ml',
    image: 'https://picsum.photos/seed/cleaner-spray/400/400',
    description: 'A powerful and eco-friendly all-purpose cleaner for your home.',
    deliveryTime: '10-15 min',
    category: 'Daily Essentials',
  },
  {
    id: 'inque-10',
    title: 'Bamboo Toothbrush',
    price: 12.00,
    weight: '1 piece',
    image: 'https://picsum.photos/seed/toothbrush/400/400',
    description: 'Sustainable and biodegradable bamboo toothbrush.',
    deliveryTime: '10-15 min',
    category: 'Daily Essentials',
  },
  { id: 'inque-de3', title: 'Toothpaste', price: 9.00, weight: '100ml', image: 'https://picsum.photos/seed/toothpaste/400/400', description: 'Fluoride toothpaste for complete dental care.', deliveryTime: '10-15 min', category: 'Daily Essentials' },
  { id: 'inque-de4', title: 'Hand Soap', price: 11.00, weight: '250ml', image: 'https://picsum.photos/seed/hand-soap/400/400', description: 'Moisturizing liquid hand soap with a pleasant scent.', deliveryTime: '10-15 min', category: 'Daily Essentials' },
  { id: 'inque-de5', title: 'Toilet Paper', price: 20.00, weight: '4 rolls', image: 'https://picsum.photos/seed/toilet-paper/400/400', description: 'Soft and strong 3-ply toilet paper.', deliveryTime: '10-15 min', category: 'Daily Essentials' },
  { id: 'inque-de6', title: 'Shampoo', price: 22.00, weight: '400ml', image: 'https://picsum.photos/seed/shampoo/400/400', description: 'Nourishing shampoo for all hair types.', deliveryTime: '10-15 min', category: 'Daily Essentials' },
  { id: 'inque-de7', title: 'Conditioner', price: 22.00, weight: '400ml', image: 'https://picsum.photos/seed/conditioner/400/400', description: 'Hydrating conditioner for smooth, shiny hair.', deliveryTime: '10-15 min', category: 'Daily Essentials' },
  { id: 'inque-de8', title: 'Dish Soap', price: 10.00, weight: '500ml', image: 'https://picsum.photos/seed/dish-soap/400/400', description: 'Tough on grease, gentle on hands.', deliveryTime: '10-15 min', category: 'Daily Essentials' },
  { id: 'inque-de9', title: 'Kitchen Paper Towels', price: 14.00, weight: '2 rolls', image: 'https://picsum.photos/seed/paper-towels/400/400', description: 'Absorbent paper towels for kitchen spills.', deliveryTime: '10-15 min', category: 'Daily Essentials' },
  { id: 'inque-de10', title: 'Trash Bags', price: 15.00, weight: '30 count', image: 'https://picsum.photos/seed/trash-bags/400/400', description: 'Durable trash bags for your kitchen bin.', deliveryTime: '10-15 min', category: 'Daily Essentials' },
  { id: 'inque-de11', title: 'Body Wash', price: 18.00, weight: '500ml', image: 'https://picsum.photos/seed/body-wash/400/400', description: 'Refreshing and cleansing body wash.', deliveryTime: '10-15 min', category: 'Daily Essentials' },
  { id: 'inque-de12', title: 'Deodorant', price: 16.00, weight: '50ml', image: 'https://picsum.photos/seed/deodorant/400/400', description: '48-hour protection roll-on deodorant.', deliveryTime: '10-15 min', category: 'Daily Essentials' },
  { id: 'inque-de13', title: 'Laundry Detergent', price: 35.00, weight: '1L', image: 'https://picsum.photos/seed/laundry-detergent/400/400', description: 'Liquid laundry detergent for clean clothes.', deliveryTime: '12-18 min', category: 'Daily Essentials' },
  { id: 'inque-de14', title: 'Sponges', price: 7.00, weight: '3 pack', image: 'https://picsum.photos/seed/sponges/400/400', description: 'A pack of 3 non-scratch kitchen sponges.', deliveryTime: '10-15 min', category: 'Daily Essentials' },
  { id: 'inque-de15', title: 'Tissues', price: 8.00, weight: '1 box', image: 'https://picsum.photos/seed/tissues/400/400', description: 'A box of soft facial tissues.', deliveryTime: '10-15 min', category: 'Daily Essentials' },
  { id: 'inque-de16', title: 'Aluminum Foil', price: 12.00, weight: '1 roll', image: 'https://picsum.photos/seed/aluminum-foil/400/400', description: 'Standard aluminum foil for cooking and storage.', deliveryTime: '10-15 min', category: 'Daily Essentials' },
  { id: 'inque-de17', title: 'Cling Film', price: 10.00, weight: '1 roll', image: 'https://picsum.photos/seed/cling-film/400/400', description: 'Plastic wrap to keep food fresh.', deliveryTime: '10-15 min', category: 'Daily Essentials' },
  { id: 'inque-de18', title: 'Batteries AA', price: 15.00, weight: '4 pack', image: 'https://picsum.photos/seed/batteries/400/400', description: 'A pack of 4 AA alkaline batteries.', deliveryTime: '10-15 min', category: 'Daily Essentials' },
  { id: 'inque-de19', title: 'Light Bulbs', price: 18.00, weight: '2 pack', image: 'https://picsum.photos/seed/light-bulbs/400/400', description: 'A 2-pack of energy-efficient LED light bulbs.', deliveryTime: '10-15 min', category: 'Daily Essentials' },
  { id: 'inque-de20', title: 'Cotton Buds', price: 6.00, weight: '200 count', image: 'https://picsum.photos/seed/cotton-buds/400/400', description: 'A pack of 200 cotton buds.', deliveryTime: '10-15 min', category: 'Daily Essentials' },
  { id: 'inque-de21', title: 'Shaving Cream', price: 14.00, weight: '200ml', image: 'https://picsum.photos/seed/shaving-cream/400/400', description: 'Rich lather shaving cream for a smooth shave.', deliveryTime: '10-15 min', category: 'Daily Essentials' },
  { id: 'inque-de22', title: 'Disposable Razors', price: 19.00, weight: '5 pack', image: 'https://picsum.photos/seed/razors/400/400', description: 'A pack of 5 disposable razors.', deliveryTime: '10-15 min', category: 'Daily Essentials' },
  { id: 'inque-de23', title: 'Hand Sanitizer', price: 9.00, weight: '100ml', image: 'https://picsum.photos/seed/hand-sanitizer/400/400', description: 'Kills 99.9% of germs on the go.', deliveryTime: '10-15 min', category: 'Daily Essentials' },
  { id: 'inque-de24', title: 'Feminine Pads', price: 17.00, weight: '1 pack', image: 'https://picsum.photos/seed/feminine-pads/400/400', description: 'A pack of regular absorbency feminine pads.', deliveryTime: '10-15 min', category: 'Daily Essentials' },
  { id: 'inque-de25', title: 'Pet Food (Cat)', price: 25.00, weight: '400g', image: 'https://picsum.photos/seed/cat-food/400/400', description: 'Dry cat food with chicken flavor.', deliveryTime: '12-18 min', category: 'Daily Essentials' },

  // Frozen (25)
  {
    id: 'inque-5',
    title: 'Frozen Peas',
    price: 9.50,
    weight: '500g',
    image: 'https://picsum.photos/seed/frozen-peas/400/400',
    description: 'Quick-frozen green peas, packed with nutrients and flavor.',
    deliveryTime: '15-20 min',
    category: 'Frozen',
  },
  {
    id: 'inque-11',
    title: 'Vanilla Bean Ice Cream',
    price: 35.00,
    weight: '500ml',
    image: 'https://picsum.photos/seed/ice-cream/400/400',
    description: 'Rich and creamy vanilla bean ice cream made with real vanilla.',
    deliveryTime: '15-20 min',
    category: 'Frozen',
  },
  { id: 'inque-f3', title: 'Frozen Strawberries', price: 18.00, weight: '500g', image: 'https://picsum.photos/seed/frozen-strawberries/400/400', description: 'Perfect for smoothies and desserts.', deliveryTime: '15-20 min', category: 'Frozen' },
  { id: 'inque-f4', title: 'Chocolate Ice Cream', price: 35.00, weight: '500ml', image: 'https://picsum.photos/seed/chocolate-ice-cream/400/400', description: 'Indulgent and rich chocolate ice cream.', deliveryTime: '15-20 min', category: 'Frozen' },
  { id: 'inque-f5', title: 'Frozen Corn', price: 9.50, weight: '500g', image: 'https://picsum.photos/seed/frozen-corn/400/400', description: 'Sweet corn kernels, frozen at peak freshness.', deliveryTime: '15-20 min', category: 'Frozen' },
  { id: 'inque-f6', title: 'Frozen Pizza Margherita', price: 28.00, weight: '400g', image: 'https://picsum.photos/seed/frozen-pizza/400/400', description: 'A classic margherita pizza, ready to bake.', deliveryTime: '15-20 min', category: 'Frozen' },
  { id: 'inque-f7', title: 'Ice Cubes', price: 10.00, weight: '2kg', image: 'https://picsum.photos/seed/ice-cubes/400/400', description: 'A large bag of ice cubes for your drinks.', deliveryTime: '15-20 min', category: 'Frozen' },
  { id: 'inque-f8', title: 'Frozen Blueberries', price: 22.00, weight: '500g', image: 'https://picsum.photos/seed/frozen-blueberries/400/400', description: 'Packed with antioxidants, great for breakfast.', deliveryTime: '15-20 min', category: 'Frozen' },
  { id: 'inque-f9', title: 'French Fries', price: 15.00, weight: '1kg', image: 'https://picsum.photos/seed/french-fries/400/400', description: 'Oven-ready french fries for a quick side dish.', deliveryTime: '15-20 min', category: 'Frozen' },
  { id: 'inque-f10', title: 'Frozen Chicken Nuggets', price: 25.00, weight: '500g', image: 'https://picsum.photos/seed/chicken-nuggets/400/400', description: 'Family-favorite chicken nuggets.', deliveryTime: '15-20 min', category: 'Frozen' },
  { id: 'inque-f11', title: 'Mango Sorbet', price: 32.00, weight: '500ml', image: 'https://picsum.photos/seed/mango-sorbet/400/400', description: 'A refreshing and dairy-free mango sorbet.', deliveryTime: '15-20 min', category: 'Frozen' },
  { id: 'inque-f12', title: 'Frozen Spinach', price: 11.00, weight: '500g', image: 'https://picsum.photos/seed/frozen-spinach/400/400', description: 'Chopped spinach, convenient for cooking.', deliveryTime: '15-20 min', category: 'Frozen' },
  { id: 'inque-f13', title: 'Frozen Fish Fillets', price: 38.00, weight: '400g', image: 'https://picsum.photos/seed/frozen-fish/400/400', description: 'Cod fillets, ready to be cooked.', deliveryTime: '15-20 min', category: 'Frozen' },
  { id: 'inque-f14', title: 'Salted Caramel Ice Cream', price: 38.00, weight: '500ml', image: 'https://picsum.photos/seed/caramel-ice-cream/400/400', description: 'Sweet and salty caramel swirl ice cream.', deliveryTime: '15-20 min', category: 'Frozen' },
  { id: 'inque-f15', title: 'Frozen Mixed Vegetables', price: 12.00, weight: '750g', image: 'https://picsum.photos/seed/mixed-veg/400/400', description: 'A mix of peas, carrots, corn, and green beans.', deliveryTime: '15-20 min', category: 'Frozen' },
  { id: 'inque-f16', title: 'Frozen Berries Mix', price: 24.00, weight: '500g', image: 'https://picsum.photos/seed/frozen-berries/400/400', description: 'A mix of strawberries, blueberries, and raspberries.', deliveryTime: '15-20 min', category: 'Frozen' },
  { id: 'inque-f17', title: 'Garlic Bread', price: 16.00, weight: '2 pack', image: 'https://picsum.photos/seed/garlic-bread/400/400', description: 'Two baguettes of frozen garlic bread.', deliveryTime: '15-20 min', category: 'Frozen' },
  { id: 'inque-f18', title: 'Ice Lollies Fruit', price: 20.00, weight: '6 pack', image: 'https://picsum.photos/seed/ice-lollies/400/400', description: 'A pack of 6 assorted fruit ice lollies.', deliveryTime: '15-20 min', category: 'Frozen' },
  { id: 'inque-f19', title: 'Frozen Edamame', price: 14.00, weight: '400g', image: 'https://picsum.photos/seed/frozen-edamame/400/400', description: 'Edamame pods, great for steaming.', deliveryTime: '15-20 min', category: 'Frozen' },
  { id: 'inque-f20', title: 'Mint Choc Chip Ice Cream', price: 36.00, weight: '500ml', image: 'https://picsum.photos/seed/mint-ice-cream/400/400', description: 'A classic combination of mint and chocolate chips.', deliveryTime: '15-20 min', category: 'Frozen' },
  { id: 'inque-f21', title: 'Frozen Broccoli Florets', price: 10.00, weight: '500g', image: 'https://picsum.photos/seed/frozen-broccoli/400/400', description: 'Convenient broccoli florets for your meals.', deliveryTime: '15-20 min', category: 'Frozen' },
  { id: 'inque-f22', title: 'Vegan Burgers', price: 30.00, weight: '2 pack', image: 'https://picsum.photos/seed/vegan-burgers/400/400', description: 'Two plant-based burger patties.', deliveryTime: '15-20 min', category: 'Frozen' },
  { id: 'inque-f23', title: 'Frozen Shrimp', price: 40.00, weight: '300g', image: 'https://picsum.photos/seed/frozen-shrimp/400/400', description: 'Peeled and deveined frozen shrimp.', deliveryTime: '15-20 min', category: 'Frozen' },
  { id: 'inque-f24', title: 'Hash Browns', price: 17.00, weight: '750g', image: 'https://picsum.photos/seed/hash-browns/400/400', description: 'Shredded potato patties, perfect for breakfast.', deliveryTime: '15-20 min', category: 'Frozen' },
  { id: 'inque-f25', title: 'Lemon Sorbet', price: 32.00, weight: '500ml', image: 'https://picsum.photos/seed/lemon-sorbet/400/400', description: 'A zesty and refreshing lemon sorbet.', deliveryTime: '15-20 min', category: 'Frozen' },

  // Bakery (25)
  {
    id: 'inque-6',
    title: 'Sourdough Bread',
    price: 25.00,
    weight: '1 loaf',
    image: 'https://picsum.photos/seed/sourdough-bread/400/400',
    description: 'Artisanal sourdough bread, freshly baked today.',
    deliveryTime: '15-20 min',
    category: 'Bakery',
  },
  {
    id: 'inque-12',
    title: 'Croissants',
    price: 18.00,
    weight: 'Pack of 2',
    image: 'https://picsum.photos/seed/croissants/400/400',
    description: 'Buttery, flaky croissants baked fresh this morning.',
    deliveryTime: '15-20 min',
    category: 'Bakery',
  },
  { id: 'inque-b3', title: 'Whole Wheat Bread', price: 15.00, weight: '1 loaf', image: 'https://picsum.photos/seed/whole-wheat-bread/400/400', description: 'A healthy and delicious loaf of whole wheat bread.', deliveryTime: '15-20 min', category: 'Bakery' },
  { id: 'inque-b4', title: 'Baguette', price: 12.00, weight: '1 loaf', image: 'https://picsum.photos/seed/baguette/400/400', description: 'A classic French baguette with a crispy crust.', deliveryTime: '15-20 min', category: 'Bakery' },
  { id: 'inque-b5', title: 'Chocolate Croissant', price: 12.00, weight: '1 piece', image: 'https://picsum.photos/seed/pain-chocolat/400/400', description: 'A flaky croissant filled with rich dark chocolate.', deliveryTime: '15-20 min', category: 'Bakery' },
  { id: 'inque-b6', title: 'Bagels', price: 16.00, weight: '4 pack', image: 'https://picsum.photos/seed/bagels/400/400', description: 'A pack of 4 classic plain bagels.', deliveryTime: '15-20 min', category: 'Bakery' },
  { id: 'inque-b7', title: 'Blueberry Muffins', price: 15.00, weight: '2 pack', image: 'https://picsum.photos/seed/blueberry-muffins/400/400', description: 'Two large muffins bursting with blueberries.', deliveryTime: '15-20 min', category: 'Bakery' },
  { id: 'inque-b8', title: 'Cinnamon Buns', price: 14.00, weight: '1 piece', image: 'https://picsum.photos/seed/cinnamon-buns/400/400', description: 'A warm, gooey cinnamon bun with cream cheese frosting.', deliveryTime: '15-20 min', category: 'Bakery' },
  { id: 'inque-b9', title: 'Cupcakes', price: 25.00, weight: '4 pack', image: 'https://picsum.photos/seed/cupcakes/400/400', description: 'A pack of 4 assorted cupcakes.', deliveryTime: '15-20 min', category: 'Bakery' },
  { id: 'inque-b10', title: 'Donuts', price: 20.00, weight: '4 pack', image: 'https://picsum.photos/seed/donuts/400/400', description: 'A pack of 4 assorted donuts.', deliveryTime: '15-20 min', category: 'Bakery' },
  { id: 'inque-b11', title: 'Banana Bread', price: 18.00, weight: '1 slice', image: 'https://picsum.photos/seed/banana-bread/400/400', description: 'A moist and delicious slice of homemade-style banana bread.', deliveryTime: '15-20 min', category: 'Bakery' },
  { id: 'inque-b12', title: 'Focaccia Bread', price: 22.00, weight: '1 piece', image: 'https://picsum.photos/seed/focaccia/400/400', description: 'Italian flatbread with rosemary and sea salt.', deliveryTime: '15-20 min', category: 'Bakery' },
  { id: 'inque-b13', title: 'English Muffins', price: 13.00, weight: '4 pack', image: 'https://picsum.photos/seed/english-muffins/400/400', description: 'Perfect for breakfast sandwiches.', deliveryTime: '15-20 min', category: 'Bakery' },
  { id: 'inque-b14', title: 'Cheesecake Slice', price: 28.00, weight: '1 slice', image: 'https://picsum.photos/seed/cheesecake/400/400', description: 'A rich and creamy New York style cheesecake slice.', deliveryTime: '15-20 min', category: 'Bakery' },
  { id: 'inque-b15', title: 'Brownie', price: 15.00, weight: '1 piece', image: 'https://picsum.photos/seed/brownie/400/400', description: 'A fudgy and decadent chocolate brownie.', deliveryTime: '15-20 min', category: 'Bakery' },
  { id: 'inque-b16', title: 'Almond Croissant', price: 14.00, weight: '1 piece', image: 'https://picsum.photos/seed/almond-croissant/400/400', description: 'A croissant with a sweet almond filling.', deliveryTime: '15-20 min', category: 'Bakery' },
  { id: 'inque-b17', title: 'Hamburger Buns', price: 10.00, weight: '4 pack', image: 'https://picsum.photos/seed/hamburger-buns/400/400', description: 'Soft buns for your burgers.', deliveryTime: '15-20 min', category: 'Bakery' },
  { id: 'inque-b18', title: 'Hot Dog Buns', price: 9.00, weight: '6 pack', image: 'https://picsum.photos/seed/hot-dog-buns/400/400', description: 'Soft buns for your hot dogs.', deliveryTime: '15-20 min', category: 'Bakery' },
  { id: 'inque-b19', title: 'Pita Bread', price: 8.00, weight: '5 pack', image: 'https://picsum.photos/seed/pita-bread/400/400', description: 'Soft and fluffy pita bread pockets.', deliveryTime: '15-20 min', category: 'Bakery' },
  { id: 'inque-b20', title: 'Scones', price: 16.00, weight: '2 pack', image: 'https://picsum.photos/seed/scones/400/400', description: 'Two plain scones, perfect with jam and cream.', deliveryTime: '15-20 min', category: 'Bakery' },
  { id: 'inque-b21', title: 'Chocolate Chip Muffin', price: 9.00, weight: '1 piece', image: 'https://picsum.photos/seed/chocolate-muffin/400/400', description: 'A muffin loaded with chocolate chips.', deliveryTime: '15-20 min', category: 'Bakery' },
  { id: 'inque-b22', title: 'Rye Bread', price: 18.00, weight: '1 loaf', image: 'https://picsum.photos/seed/rye-bread/400/400', description: 'A dense and flavorful loaf of rye bread.', deliveryTime: '15-20 min', category: 'Bakery' },
  { id: 'inque-b23', title: 'Pretzel Bun', price: 15.00, weight: '4 pack', image: 'https://picsum.photos/seed/pretzel-buns/400/400', description: 'Soft pretzel buns for sandwiches.', deliveryTime: '15-20 min', category: 'Bakery' },
  { id: 'inque-b24', title: 'Carrot Cake Slice', price: 20.00, weight: '1 slice', image: 'https://picsum.photos/seed/carrot-cake/400/400', description: 'Moist carrot cake with cream cheese frosting.', deliveryTime: '15-20 min', category: 'Bakery' },
  { id: 'inque-b25', title: 'Ciabatta Rolls', price: 14.00, weight: '4 pack', image: 'https://picsum.photos/seed/ciabatta-rolls/400/400', description: 'Crusty Italian ciabatta rolls.', deliveryTime: '15-20 min', category: 'Bakery' }
];
